name: Build - Windows
description: 'Build Windows release'

runs:
  using: "composite"
  steps:

  - name: Build cypher node
    run: |
      dotnet publish cypnode --configuration Release --self-contained -r win-x64 -p:PublishReadyToRun=true --output publish/cypnode/win-x64
      Xcopy /E /I publish/cypnode/win-x64 install/windows/cypnode_installer/node_x64_installation_files

  - name: Harvest cypher node files
    run: heat.exe dir install/windows/cypnode_installer/node_x64_installation_files -dr Node -cg NodeInstallationFilesGroup -gg -g1 -sf -srd -var "var.NodeInstallationDirectory" -out install/windows/cypnode_installer/node_installation_files.wxs


  - name: Build cypher service
    run: |
      dotnet publish install/windows/service --configuration Release --self-contained -r win-x64 -p:PublishReadyToRun=true --output publish/cypnode_service/win-x64
      Xcopy /E /I publish/cypnode_service/win-x64 install/windows/cypnode_installer/service

  - name: Harvest cypher node files
    run: heat.exe dir install/windows/cypnode_installer/service -dr Node -cg ServiceInstallationFilesGroup -gg -g1 -sf -var "var.ServiceInstallationDirectory" -t install/windows/cypnode_installer/remove_exe.xslt  -out install/windows/cypnode_installer/service_installation_files.wxs

#  - name: Package deb
#    run: |
#      cp -r install/linux/debian .
#
#      sed -i 's/\$RUNTIME/${{ inputs.runtime }}/g'                 ./debian/rules
#      sed -i "s/\$VERSION/$VERSION/g"                              ./debian/changelog
#      sed -i "s/\$TIMESTAMP/$(date +"%a, %d %b %Y %H:%M:%S %z")/g" ./debian/changelog
#
#      dpkg-buildpackage -b --no-sign -a ${{ inputs.runtime_deb }}
#
#      sha256sum ../cypher-cypnode_${{ env.VERSION }}_${{ inputs.runtime_deb }}.deb > ../cypher-cypnode_${{ env.VERSION }}_${{ inputs.runtime_deb }}.deb.sha256
#
#      mv ../*.deb        ${{ github.workspace }}
#      mv ../*.deb.sha256 ${{ github.workspace }}
#    shell: bash
